// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: bulletin_board.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostRequest) Reset() {
	*x = PostRequest{}
	mi := &file_bulletin_board_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostRequest) ProtoMessage() {}

func (x *PostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bulletin_board_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostRequest.ProtoReflect.Descriptor instead.
func (*PostRequest) Descriptor() ([]byte, []int) {
	return file_bulletin_board_proto_rawDescGZIP(), []int{0}
}

func (x *PostRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PostRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostResponse) Reset() {
	*x = PostResponse{}
	mi := &file_bulletin_board_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostResponse) ProtoMessage() {}

func (x *PostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bulletin_board_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostResponse.ProtoReflect.Descriptor instead.
func (*PostResponse) Descriptor() ([]byte, []int) {
	return file_bulletin_board_proto_rawDescGZIP(), []int{1}
}

func (x *PostResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_bulletin_board_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bulletin_board_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_bulletin_board_proto_rawDescGZIP(), []int{2}
}

func (x *ReadRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_bulletin_board_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bulletin_board_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_bulletin_board_proto_rawDescGZIP(), []int{3}
}

func (x *ReadResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ReadResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_bulletin_board_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bulletin_board_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_bulletin_board_proto_rawDescGZIP(), []int{4}
}

func (x *WatchRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type WatchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_bulletin_board_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_bulletin_board_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_bulletin_board_proto_rawDescGZIP(), []int{5}
}

func (x *WatchEvent) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *WatchEvent) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ClearRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearRequest) Reset() {
	*x = ClearRequest{}
	mi := &file_bulletin_board_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearRequest) ProtoMessage() {}

func (x *ClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bulletin_board_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearRequest.ProtoReflect.Descriptor instead.
func (*ClearRequest) Descriptor() ([]byte, []int) {
	return file_bulletin_board_proto_rawDescGZIP(), []int{6}
}

type ClearResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeysCleared   int32                  `protobuf:"varint,1,opt,name=keys_cleared,json=keysCleared,proto3" json:"keys_cleared,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearResponse) Reset() {
	*x = ClearResponse{}
	mi := &file_bulletin_board_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearResponse) ProtoMessage() {}

func (x *ClearResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bulletin_board_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearResponse.ProtoReflect.Descriptor instead.
func (*ClearResponse) Descriptor() ([]byte, []int) {
	return file_bulletin_board_proto_rawDescGZIP(), []int{7}
}

func (x *ClearResponse) GetKeysCleared() int32 {
	if x != nil {
		return x.KeysCleared
	}
	return 0
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_bulletin_board_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bulletin_board_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_bulletin_board_proto_rawDescGZIP(), []int{8}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []string               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_bulletin_board_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bulletin_board_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_bulletin_board_proto_rawDescGZIP(), []int{9}
}

func (x *ListResponse) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

var File_bulletin_board_proto protoreflect.FileDescriptor

const file_bulletin_board_proto_rawDesc = "" +
	"\n" +
	"\x14bulletin_board.proto\x12\akosh.bb\"9\n" +
	"\vPostRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x1e\n" +
	"\fPostResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"#\n" +
	"\vReadRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\":\n" +
	"\fReadResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"$\n" +
	"\fWatchRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"8\n" +
	"\n" +
	"WatchEvent\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x0e\n" +
	"\fClearRequest\"2\n" +
	"\rClearResponse\x12!\n" +
	"\fkeys_cleared\x18\x01 \x01(\x05R\vkeysCleared\"\r\n" +
	"\vListRequest\"&\n" +
	"\fListResponse\x12\x16\n" +
	"\x06topics\x18\x01 \x03(\tR\x06topics2\x9d\x02\n" +
	"\rBulletinBoard\x123\n" +
	"\x04Post\x12\x14.kosh.bb.PostRequest\x1a\x15.kosh.bb.PostResponse\x123\n" +
	"\x04Read\x12\x14.kosh.bb.ReadRequest\x1a\x15.kosh.bb.ReadResponse\x125\n" +
	"\x05Watch\x12\x15.kosh.bb.WatchRequest\x1a\x13.kosh.bb.WatchEvent0\x01\x126\n" +
	"\x05Clear\x12\x15.kosh.bb.ClearRequest\x1a\x16.kosh.bb.ClearResponse\x123\n" +
	"\x04List\x12\x14.kosh.bb.ListRequest\x1a\x15.kosh.bb.ListResponseB Z\x1egithub.com/kosh/coordinator/pbb\x06proto3"

var (
	file_bulletin_board_proto_rawDescOnce sync.Once
	file_bulletin_board_proto_rawDescData []byte
)

func file_bulletin_board_proto_rawDescGZIP() []byte {
	file_bulletin_board_proto_rawDescOnce.Do(func() {
		file_bulletin_board_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bulletin_board_proto_rawDesc), len(file_bulletin_board_proto_rawDesc)))
	})
	return file_bulletin_board_proto_rawDescData
}

var file_bulletin_board_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_bulletin_board_proto_goTypes = []any{
	(*PostRequest)(nil),   // 0: kosh.bb.PostRequest
	(*PostResponse)(nil),  // 1: kosh.bb.PostResponse
	(*ReadRequest)(nil),   // 2: kosh.bb.ReadRequest
	(*ReadResponse)(nil),  // 3: kosh.bb.ReadResponse
	(*WatchRequest)(nil),  // 4: kosh.bb.WatchRequest
	(*WatchEvent)(nil),    // 5: kosh.bb.WatchEvent
	(*ClearRequest)(nil),  // 6: kosh.bb.ClearRequest
	(*ClearResponse)(nil), // 7: kosh.bb.ClearResponse
	(*ListRequest)(nil),   // 8: kosh.bb.ListRequest
	(*ListResponse)(nil),  // 9: kosh.bb.ListResponse
}
var file_bulletin_board_proto_depIdxs = []int32{
	0, // 0: kosh.bb.BulletinBoard.Post:input_type -> kosh.bb.PostRequest
	2, // 1: kosh.bb.BulletinBoard.Read:input_type -> kosh.bb.ReadRequest
	4, // 2: kosh.bb.BulletinBoard.Watch:input_type -> kosh.bb.WatchRequest
	6, // 3: kosh.bb.BulletinBoard.Clear:input_type -> kosh.bb.ClearRequest
	8, // 4: kosh.bb.BulletinBoard.List:input_type -> kosh.bb.ListRequest
	1, // 5: kosh.bb.BulletinBoard.Post:output_type -> kosh.bb.PostResponse
	3, // 6: kosh.bb.BulletinBoard.Read:output_type -> kosh.bb.ReadResponse
	5, // 7: kosh.bb.BulletinBoard.Watch:output_type -> kosh.bb.WatchEvent
	7, // 8: kosh.bb.BulletinBoard.Clear:output_type -> kosh.bb.ClearResponse
	9, // 9: kosh.bb.BulletinBoard.List:output_type -> kosh.bb.ListResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bulletin_board_proto_init() }
func file_bulletin_board_proto_init() {
	if File_bulletin_board_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bulletin_board_proto_rawDesc), len(file_bulletin_board_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bulletin_board_proto_goTypes,
		DependencyIndexes: file_bulletin_board_proto_depIdxs,
		MessageInfos:      file_bulletin_board_proto_msgTypes,
	}.Build()
	File_bulletin_board_proto = out.File
	file_bulletin_board_proto_goTypes = nil
	file_bulletin_board_proto_depIdxs = nil
}
