// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: party.proto

package party_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PartyService_StartDkg_FullMethodName  = "/kosh.party.PartyService/StartDkg"
	PartyService_StartSign_FullMethodName = "/kosh.party.PartyService/StartSign"
	PartyService_GetStatus_FullMethodName = "/kosh.party.PartyService/GetStatus"
)

// PartyServiceClient is the client API for PartyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PartyServiceClient interface {
	StartDkg(ctx context.Context, in *DkgRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DkgEvent], error)
	StartSign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SignEvent], error)
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type partyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPartyServiceClient(cc grpc.ClientConnInterface) PartyServiceClient {
	return &partyServiceClient{cc}
}

func (c *partyServiceClient) StartDkg(ctx context.Context, in *DkgRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DkgEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PartyService_ServiceDesc.Streams[0], PartyService_StartDkg_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DkgRequest, DkgEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PartyService_StartDkgClient = grpc.ServerStreamingClient[DkgEvent]

func (c *partyServiceClient) StartSign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SignEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PartyService_ServiceDesc.Streams[1], PartyService_StartSign_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SignRequest, SignEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PartyService_StartSignClient = grpc.ServerStreamingClient[SignEvent]

func (c *partyServiceClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, PartyService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PartyServiceServer is the server API for PartyService service.
// All implementations must embed UnimplementedPartyServiceServer
// for forward compatibility.
type PartyServiceServer interface {
	StartDkg(*DkgRequest, grpc.ServerStreamingServer[DkgEvent]) error
	StartSign(*SignRequest, grpc.ServerStreamingServer[SignEvent]) error
	GetStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedPartyServiceServer()
}

// UnimplementedPartyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPartyServiceServer struct{}

func (UnimplementedPartyServiceServer) StartDkg(*DkgRequest, grpc.ServerStreamingServer[DkgEvent]) error {
	return status.Error(codes.Unimplemented, "method StartDkg not implemented")
}
func (UnimplementedPartyServiceServer) StartSign(*SignRequest, grpc.ServerStreamingServer[SignEvent]) error {
	return status.Error(codes.Unimplemented, "method StartSign not implemented")
}
func (UnimplementedPartyServiceServer) GetStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedPartyServiceServer) mustEmbedUnimplementedPartyServiceServer() {}
func (UnimplementedPartyServiceServer) testEmbeddedByValue()                      {}

// UnsafePartyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PartyServiceServer will
// result in compilation errors.
type UnsafePartyServiceServer interface {
	mustEmbedUnimplementedPartyServiceServer()
}

func RegisterPartyServiceServer(s grpc.ServiceRegistrar, srv PartyServiceServer) {
	// If the following call panics, it indicates UnimplementedPartyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PartyService_ServiceDesc, srv)
}

func _PartyService_StartDkg_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DkgRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PartyServiceServer).StartDkg(m, &grpc.GenericServerStream[DkgRequest, DkgEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PartyService_StartDkgServer = grpc.ServerStreamingServer[DkgEvent]

func _PartyService_StartSign_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SignRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PartyServiceServer).StartSign(m, &grpc.GenericServerStream[SignRequest, SignEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PartyService_StartSignServer = grpc.ServerStreamingServer[SignEvent]

func _PartyService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PartyService_ServiceDesc is the grpc.ServiceDesc for PartyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PartyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kosh.party.PartyService",
	HandlerType: (*PartyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _PartyService_GetStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartDkg",
			Handler:       _PartyService_StartDkg_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StartSign",
			Handler:       _PartyService_StartSign_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "party.proto",
}
