// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: party.proto

package party_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DkgEvent_Phase int32

const (
	DkgEvent_DKG_START        DkgEvent_Phase = 0
	DkgEvent_DKG_COMMITTED    DkgEvent_Phase = 1
	DkgEvent_DKG_REVEALED     DkgEvent_Phase = 2
	DkgEvent_DKG_SUBSHARES    DkgEvent_Phase = 3
	DkgEvent_DKG_FINALIZED    DkgEvent_Phase = 4
	DkgEvent_DKG_ZK_SUBMITTED DkgEvent_Phase = 5
	DkgEvent_DKG_COMPLETE     DkgEvent_Phase = 6
	DkgEvent_DKG_FAILED       DkgEvent_Phase = 7
)

// Enum value maps for DkgEvent_Phase.
var (
	DkgEvent_Phase_name = map[int32]string{
		0: "DKG_START",
		1: "DKG_COMMITTED",
		2: "DKG_REVEALED",
		3: "DKG_SUBSHARES",
		4: "DKG_FINALIZED",
		5: "DKG_ZK_SUBMITTED",
		6: "DKG_COMPLETE",
		7: "DKG_FAILED",
	}
	DkgEvent_Phase_value = map[string]int32{
		"DKG_START":        0,
		"DKG_COMMITTED":    1,
		"DKG_REVEALED":     2,
		"DKG_SUBSHARES":    3,
		"DKG_FINALIZED":    4,
		"DKG_ZK_SUBMITTED": 5,
		"DKG_COMPLETE":     6,
		"DKG_FAILED":       7,
	}
)

func (x DkgEvent_Phase) Enum() *DkgEvent_Phase {
	p := new(DkgEvent_Phase)
	*p = x
	return p
}

func (x DkgEvent_Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DkgEvent_Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_party_proto_enumTypes[0].Descriptor()
}

func (DkgEvent_Phase) Type() protoreflect.EnumType {
	return &file_party_proto_enumTypes[0]
}

func (x DkgEvent_Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DkgEvent_Phase.Descriptor instead.
func (DkgEvent_Phase) EnumDescriptor() ([]byte, []int) {
	return file_party_proto_rawDescGZIP(), []int{1, 0}
}

type SignEvent_Phase int32

const (
	SignEvent_SIGN_START    SignEvent_Phase = 0
	SignEvent_PQC_APPROVED  SignEvent_Phase = 1
	SignEvent_GG20_ROUND1   SignEvent_Phase = 2
	SignEvent_MTA_COMPLETE  SignEvent_Phase = 3
	SignEvent_GG20_ROUND2   SignEvent_Phase = 4
	SignEvent_PARTIAL_SIGS  SignEvent_Phase = 5
	SignEvent_SIGN_COMPLETE SignEvent_Phase = 6
	SignEvent_SIGN_FAILED   SignEvent_Phase = 7
)

// Enum value maps for SignEvent_Phase.
var (
	SignEvent_Phase_name = map[int32]string{
		0: "SIGN_START",
		1: "PQC_APPROVED",
		2: "GG20_ROUND1",
		3: "MTA_COMPLETE",
		4: "GG20_ROUND2",
		5: "PARTIAL_SIGS",
		6: "SIGN_COMPLETE",
		7: "SIGN_FAILED",
	}
	SignEvent_Phase_value = map[string]int32{
		"SIGN_START":    0,
		"PQC_APPROVED":  1,
		"GG20_ROUND1":   2,
		"MTA_COMPLETE":  3,
		"GG20_ROUND2":   4,
		"PARTIAL_SIGS":  5,
		"SIGN_COMPLETE": 6,
		"SIGN_FAILED":   7,
	}
)

func (x SignEvent_Phase) Enum() *SignEvent_Phase {
	p := new(SignEvent_Phase)
	*p = x
	return p
}

func (x SignEvent_Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignEvent_Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_party_proto_enumTypes[1].Descriptor()
}

func (SignEvent_Phase) Type() protoreflect.EnumType {
	return &file_party_proto_enumTypes[1]
}

func (x SignEvent_Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignEvent_Phase.Descriptor instead.
func (SignEvent_Phase) EnumDescriptor() ([]byte, []int) {
	return file_party_proto_rawDescGZIP(), []int{3, 0}
}

type DkgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         uint32                 `protobuf:"varint,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	NumParties    uint32                 `protobuf:"varint,2,opt,name=num_parties,json=numParties,proto3" json:"num_parties,omitempty"`
	Threshold     uint32                 `protobuf:"varint,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DkgRequest) Reset() {
	*x = DkgRequest{}
	mi := &file_party_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DkgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DkgRequest) ProtoMessage() {}

func (x *DkgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_party_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DkgRequest.ProtoReflect.Descriptor instead.
func (*DkgRequest) Descriptor() ([]byte, []int) {
	return file_party_proto_rawDescGZIP(), []int{0}
}

func (x *DkgRequest) GetKeyId() uint32 {
	if x != nil {
		return x.KeyId
	}
	return 0
}

func (x *DkgRequest) GetNumParties() uint32 {
	if x != nil {
		return x.NumParties
	}
	return 0
}

func (x *DkgRequest) GetThreshold() uint32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

type DkgEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         DkgEvent_Phase         `protobuf:"varint,1,opt,name=phase,proto3,enum=kosh.party.DkgEvent_Phase" json:"phase,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DkgEvent) Reset() {
	*x = DkgEvent{}
	mi := &file_party_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DkgEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DkgEvent) ProtoMessage() {}

func (x *DkgEvent) ProtoReflect() protoreflect.Message {
	mi := &file_party_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DkgEvent.ProtoReflect.Descriptor instead.
func (*DkgEvent) Descriptor() ([]byte, []int) {
	return file_party_proto_rawDescGZIP(), []int{1}
}

func (x *DkgEvent) GetPhase() DkgEvent_Phase {
	if x != nil {
		return x.Phase
	}
	return DkgEvent_DKG_START
}

func (x *DkgEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         uint32                 `protobuf:"varint,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	MessageHash   []byte                 `protobuf:"bytes,2,opt,name=message_hash,json=messageHash,proto3" json:"message_hash,omitempty"`
	TxTag         string                 `protobuf:"bytes,3,opt,name=tx_tag,json=txTag,proto3" json:"tx_tag,omitempty"`
	SigningSubset []uint32               `protobuf:"varint,4,rep,packed,name=signing_subset,json=signingSubset,proto3" json:"signing_subset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_party_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_party_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_party_proto_rawDescGZIP(), []int{2}
}

func (x *SignRequest) GetKeyId() uint32 {
	if x != nil {
		return x.KeyId
	}
	return 0
}

func (x *SignRequest) GetMessageHash() []byte {
	if x != nil {
		return x.MessageHash
	}
	return nil
}

func (x *SignRequest) GetTxTag() string {
	if x != nil {
		return x.TxTag
	}
	return ""
}

func (x *SignRequest) GetSigningSubset() []uint32 {
	if x != nil {
		return x.SigningSubset
	}
	return nil
}

type SignEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         SignEvent_Phase        `protobuf:"varint,1,opt,name=phase,proto3,enum=kosh.party.SignEvent_Phase" json:"phase,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignEvent) Reset() {
	*x = SignEvent{}
	mi := &file_party_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignEvent) ProtoMessage() {}

func (x *SignEvent) ProtoReflect() protoreflect.Message {
	mi := &file_party_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignEvent.ProtoReflect.Descriptor instead.
func (*SignEvent) Descriptor() ([]byte, []int) {
	return file_party_proto_rawDescGZIP(), []int{3}
}

func (x *SignEvent) GetPhase() SignEvent_Phase {
	if x != nil {
		return x.Phase
	}
	return SignEvent_SIGN_START
}

func (x *SignEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SignEvent) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_party_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_party_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_party_proto_rawDescGZIP(), []int{4}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyIndex    uint32                 `protobuf:"varint,1,opt,name=party_index,json=partyIndex,proto3" json:"party_index,omitempty"`
	CurrentPhase  string                 `protobuf:"bytes,2,opt,name=current_phase,json=currentPhase,proto3" json:"current_phase,omitempty"`
	ActiveKeyIds  []uint32               `protobuf:"varint,3,rep,packed,name=active_key_ids,json=activeKeyIds,proto3" json:"active_key_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_party_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_party_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_party_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetPartyIndex() uint32 {
	if x != nil {
		return x.PartyIndex
	}
	return 0
}

func (x *StatusResponse) GetCurrentPhase() string {
	if x != nil {
		return x.CurrentPhase
	}
	return ""
}

func (x *StatusResponse) GetActiveKeyIds() []uint32 {
	if x != nil {
		return x.ActiveKeyIds
	}
	return nil
}

var File_party_proto protoreflect.FileDescriptor

const file_party_proto_rawDesc = "" +
	"\n" +
	"\vparty.proto\x12\n" +
	"kosh.party\"b\n" +
	"\n" +
	"DkgRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\rR\x05keyId\x12\x1f\n" +
	"\vnum_parties\x18\x02 \x01(\rR\n" +
	"numParties\x12\x1c\n" +
	"\tthreshold\x18\x03 \x01(\rR\tthreshold\"\xf2\x01\n" +
	"\bDkgEvent\x120\n" +
	"\x05phase\x18\x01 \x01(\x0e2\x1a.kosh.party.DkgEvent.PhaseR\x05phase\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x99\x01\n" +
	"\x05Phase\x12\r\n" +
	"\tDKG_START\x10\x00\x12\x11\n" +
	"\rDKG_COMMITTED\x10\x01\x12\x10\n" +
	"\fDKG_REVEALED\x10\x02\x12\x11\n" +
	"\rDKG_SUBSHARES\x10\x03\x12\x11\n" +
	"\rDKG_FINALIZED\x10\x04\x12\x14\n" +
	"\x10DKG_ZK_SUBMITTED\x10\x05\x12\x10\n" +
	"\fDKG_COMPLETE\x10\x06\x12\x0e\n" +
	"\n" +
	"DKG_FAILED\x10\a\"\x85\x01\n" +
	"\vSignRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\rR\x05keyId\x12!\n" +
	"\fmessage_hash\x18\x02 \x01(\fR\vmessageHash\x12\x15\n" +
	"\x06tx_tag\x18\x03 \x01(\tR\x05txTag\x12%\n" +
	"\x0esigning_subset\x18\x04 \x03(\rR\rsigningSubset\"\x8c\x02\n" +
	"\tSignEvent\x121\n" +
	"\x05phase\x18\x01 \x01(\x0e2\x1b.kosh.party.SignEvent.PhaseR\x05phase\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"\x93\x01\n" +
	"\x05Phase\x12\x0e\n" +
	"\n" +
	"SIGN_START\x10\x00\x12\x10\n" +
	"\fPQC_APPROVED\x10\x01\x12\x0f\n" +
	"\vGG20_ROUND1\x10\x02\x12\x10\n" +
	"\fMTA_COMPLETE\x10\x03\x12\x0f\n" +
	"\vGG20_ROUND2\x10\x04\x12\x10\n" +
	"\fPARTIAL_SIGS\x10\x05\x12\x11\n" +
	"\rSIGN_COMPLETE\x10\x06\x12\x0f\n" +
	"\vSIGN_FAILED\x10\a\"\x0f\n" +
	"\rStatusRequest\"|\n" +
	"\x0eStatusResponse\x12\x1f\n" +
	"\vparty_index\x18\x01 \x01(\rR\n" +
	"partyIndex\x12#\n" +
	"\rcurrent_phase\x18\x02 \x01(\tR\fcurrentPhase\x12$\n" +
	"\x0eactive_key_ids\x18\x03 \x03(\rR\factiveKeyIds2\xcd\x01\n" +
	"\fPartyService\x12:\n" +
	"\bStartDkg\x12\x16.kosh.party.DkgRequest\x1a\x14.kosh.party.DkgEvent0\x01\x12=\n" +
	"\tStartSign\x12\x17.kosh.party.SignRequest\x1a\x15.kosh.party.SignEvent0\x01\x12B\n" +
	"\tGetStatus\x12\x19.kosh.party.StatusRequest\x1a\x1a.kosh.party.StatusResponseB\x1aZ\x18github.com/kosh/party/pbb\x06proto3"

var (
	file_party_proto_rawDescOnce sync.Once
	file_party_proto_rawDescData []byte
)

func file_party_proto_rawDescGZIP() []byte {
	file_party_proto_rawDescOnce.Do(func() {
		file_party_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_party_proto_rawDesc), len(file_party_proto_rawDesc)))
	})
	return file_party_proto_rawDescData
}

var file_party_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_party_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_party_proto_goTypes = []any{
	(DkgEvent_Phase)(0),    // 0: kosh.party.DkgEvent.Phase
	(SignEvent_Phase)(0),   // 1: kosh.party.SignEvent.Phase
	(*DkgRequest)(nil),     // 2: kosh.party.DkgRequest
	(*DkgEvent)(nil),       // 3: kosh.party.DkgEvent
	(*SignRequest)(nil),    // 4: kosh.party.SignRequest
	(*SignEvent)(nil),      // 5: kosh.party.SignEvent
	(*StatusRequest)(nil),  // 6: kosh.party.StatusRequest
	(*StatusResponse)(nil), // 7: kosh.party.StatusResponse
}
var file_party_proto_depIdxs = []int32{
	0, // 0: kosh.party.DkgEvent.phase:type_name -> kosh.party.DkgEvent.Phase
	1, // 1: kosh.party.SignEvent.phase:type_name -> kosh.party.SignEvent.Phase
	2, // 2: kosh.party.PartyService.StartDkg:input_type -> kosh.party.DkgRequest
	4, // 3: kosh.party.PartyService.StartSign:input_type -> kosh.party.SignRequest
	6, // 4: kosh.party.PartyService.GetStatus:input_type -> kosh.party.StatusRequest
	3, // 5: kosh.party.PartyService.StartDkg:output_type -> kosh.party.DkgEvent
	5, // 6: kosh.party.PartyService.StartSign:output_type -> kosh.party.SignEvent
	7, // 7: kosh.party.PartyService.GetStatus:output_type -> kosh.party.StatusResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_party_proto_init() }
func file_party_proto_init() {
	if File_party_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_party_proto_rawDesc), len(file_party_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_party_proto_goTypes,
		DependencyIndexes: file_party_proto_depIdxs,
		EnumInfos:         file_party_proto_enumTypes,
		MessageInfos:      file_party_proto_msgTypes,
	}.Build()
	File_party_proto = out.File
	file_party_proto_goTypes = nil
	file_party_proto_depIdxs = nil
}
